Add datasets
NASA-IMPACT/cloud-optimized-data-pipelines pull request #311
Opened 2023-03-10 17:06 UTC by slesaad

# Changes
- Added dataset definitions for datasets needed for EIS discoveries

2023-03-13 20:28 UTC, moradology commented on data/datasets/lis-da-gpp-trend.json
> +        "filename_regex": "(.*)DAGPP_STL_based_trendv2_2003_2021.cog.tif$",
Should change to "(.*)DAGPP_STL_based_trend_v3_2003_2021.cog.tif$"

2023-03-13 20:29 UTC, moradology commented on data/datasets/lis-da-tws-trend.json
> +      "filename_regex": "(.*)DATWS_STL_based_trendv2_2003_2021.cog.tif$",
Should change to "(.*)DATWS_STL_based_trend_v3_2003_2021.cog.tif$"

2023-03-13 20:29 UTC, moradology requested changes
A couple small edits to point to updated files

2023-09-22 11:27 UTC, gadomski commented
This repo is being sunsetted (https://github.com/NASA-IMPACT/veda-data-pipelines/pull/360), so we are closing all open PRs. Please re-open on https://github.com/NASA-IMPACT/veda-data if needed.

2023-09-22 11:27 UTC, closed without merging